display_name: Otoscopia
publisher_display_name: laurencetroyv
identity_name: com.laurencetroyv.otoscopia
msix_version: 1.0.0.0
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient, location, webcam
languages: en-us
publisher: CN=laurencetroyv, O=Otoscopia MD, C=PH
certificate_path: C:\certs\otoscopia.pfx
# Uncomment the following line and replace the value with the password for the certificate
# certificate_password: Aa12345678