import 'constants.dart';

const String kSignInBtn = "Sign In";
const String kSignUpBtn = "Sign Up";
const String kDocsBtn = "Docs";
const String kNewsBtn = "News";
const String kGoBackBtn = "Go back";
const String kFAQBtn = "FAQ";
const String kPrivacyPolicyBtn = "Privacy Policy";
const String kTermsAndConditionsBtn = "Terms and Conditions";
const String kEmailNowBtn = "Email Now.";
const String kMailToBtn = "mailto:$kEmail";
const String kNoAccount = "No account? Sign up";
const String kAccountNotAccessible = "Can't access your account?";
const String kUpdateBtn = "Update";
const String kContinueBtn = "Continue";
const String kSwitchCameraBtn = 'Switch Camera';
const String kCaptureBtn = 'Capture';
const String kInitializeCamera = 'Initialize Camera';
const String kRefreshBtn = 'Refresh';
const String kAddPatientBtn = 'Add Patient';
const String kModifyBtn = 'Modify';
const String kPrintBtn = 'Print';
const String kPatientDetails = 'Patient Details';
const String kSaveBtn = 'Save';
const String kCancelBtn = 'Cancel';