export 'button_constants.dart';
export 'guest_constants.dart';
export 'named_routes_constants.dart';
export 'nurse_constants.dart';
export 'settings_constants.dart';

const String kAppName = 'Otoscopia';
const String kMultiPlatform = 'A Multi-Platform Application';
const String kDiscoverYourEarHealth = 'Discover your ear health with a simple test, and get a diagnosis with the help of a doctor.';
const String kOffline = 'Offline';
const String kInitialRoute = "/";
const String kLogo = 'assets/otoscopia.svg';
const String kSettings = 'Settings';
const String kProfile = 'Profile';
const String kLogout = 'Logout';
const String kDashboard = 'Dashboard';
const String kPatients = 'Patients';
const String kSchools = 'Schools';
const String kNurse = 'Nurse';
const String kDoctor = 'Doctor';
const String kSearch = 'Search';
const String kHome = 'Home';
const String kNoDataAvailable = 'No data available';
const String kName = 'Name';
const String kAgeAndGender = 'Age/Gender';
const String kStatus = 'Status';
const String kSchool = 'School';
const String kPending = 'Pending';
const String kFollowUp = 'Follow Up';
const String kMedicalAttention = 'Medical Attention';
const String kResolved = 'Resolved';
const String kAddPatient = 'Add New Patient';
const String kErrorTitle = 'Ohh oh!';
const String kErrorMessage = 'Please input all data before proceeding to the next step.';
const String kWorkAddress = "Work Address";
const String kAbbr = "Abbr.";
const String kAddress = "Address";
const String kAssignedNurse = "Assigned Nurse:";
const String kAssignedDoctor = "Assigned Doctor:";
const String kPatientCode = "Patient Code:";
const String kLeftEar = "Left Ear";
const String kRightEar = "Right Ear";